name: voler-learning
recipe: laravel
config:
  php: '8.1'
  webroot: public
  composer_version: '2.2.0'
services:
  node:
    type: node:16
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm install
  phpmyadmin:
    type: phpmyadmin
    hosts:
      - database
tooling:
  dev:
    service: node
    cmd: npm run dev
  build:
    service: node
    cmd: npm run build
proxy:
  phpmyadmin:
    - phpmyadmin.voler-learning.lndo.site
